In [1]:
import numpy as np

a=np.array([[0,1],[2,3],[4,5]])
b=np.array([[0,1,2,3],[4,5,6,7]])

result=np.dot(a,b)
print("積の結果\n",result)

max_value=np.max(result)
print("最大値",max_value)


積の結果
 [[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
最大値 47
